### PR TITLE
Dockerfile for github actions

### PR DESCRIPTION
**Pull request by alex0107**

### CODE REVIEW

**Comment by navid-kalaei** [comment]
I tried to run the docker file on my local machine, but it failed. here is log.
```
E: Failed to fetch http://deb.debian.org/debian/pool/main/a/apparmor/libapparmor1_2.13.2-10_amd64.deb  Connection failed [IP: 199.232.138.132 80]
E: Failed to fetch http://deb.debian.org/debian/pool/main/d/dbus/libdbus-1-3_1.12.20-0+deb10u1_amd64.deb  Connection failed [IP: 199.232.138.132 80]
E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?
Error response from daemon: The command '/bin/sh -c apt-get install -y git python3 python3-dev build-essential libc6 libffi-dev python3-pip python3-venv' returned a non-zero code: 100
Failed to deploy '<unknown> Dockerfile: Dockerfile': Can't retrieve image ID from build stream

**Comment by alex0107** [comment]
I think you should use docker run -d <kartevonmorgen> -p 3000:3000

**Comment by navid-kalaei** [comment]
the output of `docker run -d  <image id> -p 3000:3000/tcp` 

```
[eval]:1
3000:3000/tcp
    ^

SyntaxError: Unexpected token ':'
    at new Script (node:vm:100:7)
    at createScript (node:vm:257:10)
    at Object.runInThisContext (node:vm:305:10)
    at node:internal/process/execution:75:19
    at [eval]-wrapper:6:22
    at evalScript (node:internal/process/execution:74:60)
    at node:internal/main/eval_string:27:3
```

**Comment by navid-kalaei** [comment]
the docker file is healthy. however it only builds and runs the front-end project, the tag-synchronizer excluded

**Review by navid-kalaei — APPROVED** [review]
the docker file is healthy. however it only builds and runs the front-end project, the tag-synchronizer excluded

**Pull request merged**
